using System;
using System.Collections.Generic;

namespace WebKPIR.Model.Ksiega
{
    public partial class Pit5
    {
        public string Nip { get; set; }
        public string McRok { get; set; }
        public string Urzad { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string DataUr { get; set; }
        public string Kraj { get; set; }
        public string Wojew { get; set; }
        public string Powiat { get; set; }
        public string Gmina { get; set; }
        public string Ulica { get; set; }
        public string Numer { get; set; }
        public string Mieszk { get; set; }
        public string Miejsc { get; set; }
        public string KodP { get; set; }
        public string Poczta { get; set; }
        public double? C19 { get; set; }
        public double? C20 { get; set; }
        public double? C21 { get; set; }
        public double? C22 { get; set; }
        public double? C23 { get; set; }
        public double? C24 { get; set; }
        public double? C25 { get; set; }
        public double? C26 { get; set; }
        public double? C27 { get; set; }
        public double? C28 { get; set; }
        public double? C29 { get; set; }
        public double? C30 { get; set; }
        public double? D31 { get; set; }
        public double? D32 { get; set; }
        public double? D33 { get; set; }
        public double? E34 { get; set; }
        public double? E35 { get; set; }
        public double? E36 { get; set; }
        public double? E37 { get; set; }
        public double? E38 { get; set; }
        public double? E39 { get; set; }
        public double? E40 { get; set; }
        public double? E41 { get; set; }
        public string E42 { get; set; }
        public double? E43 { get; set; }
        public double? F44 { get; set; }
        public double? F45 { get; set; }
        public double? G46 { get; set; }
        public double? H47 { get; set; }
        public double? I48 { get; set; }
        public double? I49 { get; set; }
        public double? J50 { get; set; }
        public double? J51 { get; set; }
        public double? J52 { get; set; }
        public double? J53 { get; set; }
        public double? Ogran { get; set; }
        public double? Zanie { get; set; }
        public string J54 { get; set; }
        public double? J55 { get; set; }
        public string J56 { get; set; }
        public double? J57 { get; set; }
        public double? J58 { get; set; }
        public double? J59 { get; set; }
        public double? J60 { get; set; }
        public double? J61 { get; set; }
        public double? J62 { get; set; }
        public double? J63 { get; set; }
        public string K64 { get; set; }
        public string K65 { get; set; }
        public string K66 { get; set; }
        public string K67 { get; set; }
        public double? K68 { get; set; }
        public double? K69 { get; set; }
        public double? K70 { get; set; }
        public double? K71 { get; set; }
        public double? K72 { get; set; }
        public string K73 { get; set; }
        public string K74 { get; set; }
        public string K75 { get; set; }
        public string K76 { get; set; }
        public double? K77 { get; set; }
        public double? K78 { get; set; }
        public double? K79 { get; set; }
        public double? K80 { get; set; }
        public double? K81 { get; set; }
        public string L82 { get; set; }
        public string L83 { get; set; }
        public string L84 { get; set; }
        public string L85 { get; set; }
        public string L86 { get; set; }
        public string L87 { get; set; }
        public string L88 { get; set; }
        public string L89 { get; set; }
        public string L90 { get; set; }
        public double? L91 { get; set; }
        public double? L92 { get; set; }
        public double? L93 { get; set; }
        public double? L94 { get; set; }
        public double? L95 { get; set; }
        public double? L96 { get; set; }
        public double? L97 { get; set; }
        public string L98 { get; set; }
        public string L99 { get; set; }
        public string L100 { get; set; }
        public string L101 { get; set; }
        public string L102 { get; set; }
        public string L103 { get; set; }
        public string L104 { get; set; }
        public string L105 { get; set; }
        public string L106 { get; set; }
        public double? L107 { get; set; }
        public double? L108 { get; set; }
        public double? L109 { get; set; }
        public double? L110 { get; set; }
        public double? L111 { get; set; }
        public double? L112 { get; set; }
        public double? L113 { get; set; }
        public string M114 { get; set; }
        public string M115 { get; set; }
        public double? M116 { get; set; }
        public double? M117 { get; set; }
        public double? M118 { get; set; }
        public double? M119 { get; set; }
        public double? M120 { get; set; }
        public string M121 { get; set; }
        public string M122 { get; set; }
        public double? M123 { get; set; }
        public double? M124 { get; set; }
        public double? M125 { get; set; }
        public double? M126 { get; set; }
        public double? M127 { get; set; }
        public double? N128 { get; set; }
        public double? N129 { get; set; }
        public double? N130 { get; set; }
        public string O131 { get; set; }
    }
}
