using System;
using System.Collections.Generic;

namespace WebKPIR.Model.Ksiega
{
    public partial class Wspolnik
    {
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Kraj { get; set; }
        public string Wojewodztw { get; set; }
        public string Powiat { get; set; }
        public string Gmina { get; set; }
        public string Ulica { get; set; }
        public string Nrdomu { get; set; }
        public string Nrlokalu { get; set; }
        public string Miejscowos { get; set; }
        public string Kod { get; set; }
        public string Poczta { get; set; }
        public string Urzadskarb { get; set; }
        public string NipKod { get; set; }
        public string Nip { get; set; }
        public string Pesel { get; set; }
        public string Bank { get; set; }
        public string Konto { get; set; }
        public DateTime? Dataurodze { get; set; }
        public double? Zus01 { get; set; }
        public double? Zus02 { get; set; }
        public double? Zus03 { get; set; }
        public double? Zus04 { get; set; }
        public double? Zus05 { get; set; }
        public double? Zus06 { get; set; }
        public double? Zus07 { get; set; }
        public double? Zus08 { get; set; }
        public double? Zus09 { get; set; }
        public double? Zus10 { get; set; }
        public double? Zus11 { get; set; }
        public double? Zus12 { get; set; }
        public double? Ub01 { get; set; }
        public double? Ub02 { get; set; }
        public double? Ub03 { get; set; }
        public double? Ub04 { get; set; }
        public double? Ub05 { get; set; }
        public double? Ub06 { get; set; }
        public double? Ub07 { get; set; }
        public double? Ub08 { get; set; }
        public double? Ub09 { get; set; }
        public double? Ub10 { get; set; }
        public double? Ub11 { get; set; }
        public double? Ub12 { get; set; }
        public double? C1901 { get; set; }
        public double? C1902 { get; set; }
        public double? C1903 { get; set; }
        public double? C1904 { get; set; }
        public double? C1905 { get; set; }
        public double? C1906 { get; set; }
        public double? C1907 { get; set; }
        public double? C1908 { get; set; }
        public double? C1909 { get; set; }
        public double? C1910 { get; set; }
        public double? C1911 { get; set; }
        public double? C1912 { get; set; }
        public double? Naudz01 { get; set; }
        public double? Naudz02 { get; set; }
        public double? Naudz03 { get; set; }
        public double? Naudz04 { get; set; }
        public double? Naudz05 { get; set; }
        public double? Naudz06 { get; set; }
        public double? Naudz07 { get; set; }
        public double? Naudz08 { get; set; }
        public double? Naudz09 { get; set; }
        public double? Naudz10 { get; set; }
        public double? Naudz11 { get; set; }
        public double? Naudz12 { get; set; }
        public double? Naprz01 { get; set; }
        public double? Naprz02 { get; set; }
        public double? Naprz03 { get; set; }
        public double? Naprz04 { get; set; }
        public double? Naprz05 { get; set; }
        public double? Naprz06 { get; set; }
        public double? Naprz07 { get; set; }
        public double? Naprz08 { get; set; }
        public double? Naprz09 { get; set; }
        public double? Naprz10 { get; set; }
        public double? Naprz11 { get; set; }
        public double? Naprz12 { get; set; }
        public double? Nakos01 { get; set; }
        public double? Nakos02 { get; set; }
        public double? Nakos03 { get; set; }
        public double? Nakos04 { get; set; }
        public double? Nakos05 { get; set; }
        public double? Nakos06 { get; set; }
        public double? Nakos07 { get; set; }
        public double? Nakos08 { get; set; }
        public double? Nakos09 { get; set; }
        public double? Nakos10 { get; set; }
        public double? Nakos11 { get; set; }
        public double? Nakos12 { get; set; }
        public double? Procent { get; set; }
        public double? Udzial01 { get; set; }
        public double? Udzial02 { get; set; }
        public double? Udzial03 { get; set; }
        public double? Udzial04 { get; set; }
        public double? Udzial05 { get; set; }
        public double? Udzial06 { get; set; }
        public double? Udzial07 { get; set; }
        public double? Udzial08 { get; set; }
        public double? Udzial09 { get; set; }
        public double? Udzial10 { get; set; }
        public double? Udzial11 { get; set; }
        public double? Udzial12 { get; set; }
        public string Nanip { get; set; }
        public string Namiejsce { get; set; }
        public string Nanipe { get; set; }
        public string Namiejscee { get; set; }
        public double? Naudz01e { get; set; }
        public double? Naudz02e { get; set; }
        public double? Naudz03e { get; set; }
        public double? Naudz04e { get; set; }
        public double? Naudz05e { get; set; }
        public double? Naudz06e { get; set; }
        public double? Naudz07e { get; set; }
        public double? Naudz08e { get; set; }
        public double? Naudz09e { get; set; }
        public double? Naudz10e { get; set; }
        public double? Naudz11e { get; set; }
        public double? Naudz12e { get; set; }
        public bool PodLin { get; set; }
        public string KodTUb { get; set; }
        public string Dowod { get; set; }
        public double? PodOkres { get; set; }
        public string ZusWsp { get; set; }
    }
}
